### ISSUE TITLE
Test script expects mroonga_libgroonga_version is same as mroonga_version

### ISSUE THREAD

**Issue by yoku0825** [mroonga/docker#2]
* Currently, test script expects mroonga_libgroonga_version is same as mroonga_version.
  * Expected version number is generated from directory name.
  * https://github.com/mroonga/docker/blob/master/test/build.pl#L113-L117

* But Groonga and Mroonga don't have same version completely.
  * For example, Mroonga 4.10 and Groonga 4.1.1 is right couple at 2015/01/29's release.

**Comment by yoku0825** [comment]
1. Include Groonga's version into directory name.
  * ex) mysql5627_mroonga508_groonga508
  * I don't like this :(

1. Make a file written couple of Groonga and Mroonga's version
  * YAML, JSON, ..

**Comment by kou** [comment]
Groonga and Mroonga will use the same version!
For example, Mroonga 5.08 was released instead of 5.07.

**Comment by yoku0825** [comment]
> Groonga and Mroonga will use the same version!
I remember Mroonga 3.x series and 5.x series are exactly using the same version.
But 4.x series were not.
[4.03 was released](https://osdn.jp/projects/groonga/lists/archive/dev/2014-May/002373.html) at May 2014 and [4.04 was released](https://osdn.jp/projects/groonga/lists/archive/dev/2014-August/002572.html) at July 2014.

I have a plan to build Mroonga 4.10(the last release of 4.x series)'s image, should I plan it outside of this repository?
(Hi.. Can you here me..? I'm talking your mind directly.. Is anyone who would like to use 4.x series..?)

**Comment by kou** [comment]
> I have a plan to build Mroonga 4.10(the last release of 4.x series)'s image, should I plan it outside of this repository?

You can do it on this repository!

**Comment by yoku0825** [comment]
I got it!!

Now we can write couples of MySQL version, Mroonga version, Groonga version by JSON like this.
https://github.com/yoku0825/docker/blob/4834479e54915119dcdb23528450dd3268124ea3/test/version.json

Oops.. do you love YAML than JSON? :)

**Comment by yoku0825** [comment]
Mroonga 4.10's dockerfile is ready.
I can release its image after #5 merging.

**Comment by kou** [comment]
I prefer to YAML as format for writing by human. But it's not important.

**Comment by yoku0825** [comment]
> I prefer to YAML as format for writing by human.
Wow.. I'm surprised..
(Why I implement that by JSON is I think you like JSON more than YAML..)

> But it's not important.
Yep ;)

#5 had been merged and I close this. Thank you!!

**Comment by kou** [comment]
> Wow.. I'm surprised..
> (Why I implement that by JSON is I think you like JSON more than YAML..)

Oh... I don't like the last "," isn't optional in JSON...
