### ISSUE TITLE
Using tag for new autobuild manner in Docker Hub

### ISSUE THREAD

**Issue by yoku0825** [mroonga/docker#66]
[Docker \- I have issues triggering Autobuilds](https://success.docker.com/article/i-have-issues-triggering-autobuilds)

- Sample

![](https://user-images.githubusercontent.com/2453622/53911918-9ed42800-400c-11e9-99db-186c249406b3.png)

**Comment by kou** [comment]
Can I help this?
Do we want to use the following directory structure and tag for each version, right?

```text
docker/Dockerfile
docker/entrypoint.sh
docker/my.cnf
README.md
test/build.pl
test/cpanfile
test/version.json
````

**Comment by yoku0825** [comment]
Thank you, @kou !

Please help me!
I'm in progress on [this branch](https://github.com/mroonga/docker/tree/refactor_for_tag) but I can't take a time for this..

**Comment by kou** [comment]
I see.
I take over this.

**Comment by kou** [comment]
The current `Dockerfile/Dockerfile` approach isn't suitable for maintaining both MySQL 5.6 and 5.7.
I'll use `mysql-56/{Dockerfile,entrypoint.sh,my.cnf}` and `mysql-57/{Dockerfile,entrypoint.sh,my.cnf}`.

**Comment by kou** [comment]
Done.

**Comment by yoku0825** [comment]
Fantastic! Thank you!
