### ISSUE TITLE
[Question] What's the proper way to initialize DB automatically?

### ISSUE THREAD

**Issue by tmsick** [mroonga/docker#69]
I want to initialize the schema of Mroonga DB with SQL files. MySQL and PostgreSQL images read `/docker-entrypoint-initdb.d` directory on the first boot and if there are `.sql` files there, they automatically run the files. I want to do the same thing with this Mroonga image. Is there any way to achieve that?

**Comment by kou** [comment]
We want to change base image to MySQL's official image from `centos:7`.
We need to build Mroonga packages against MySQL packages for Debian GNU/Linux to do this.

**Comment by tmsick** [comment]
Then, for now, there is no way to achieve the auto-initialization, is there?

**Comment by kou** [comment]
Yes.

**Comment by tmsick** [comment]
OK. I will write wrapper script for now. Thank you for gentle support.

**Comment by kou** [comment]
Now, our images are based on the official MySQL images.

**Comment by tmsick** [comment]
What a good job! Thank you for notifying!🎉
