### ISSUE TITLE
Update the version above 10.03 as soon as possible. There are serious bugs in 10.03

### ISSUE THREAD

**Issue by mmm8955405** [mroonga/docker#71]
After the release of mroonga version 11.03, there was a serious bug. There was a syntax parsing error in testing special characters
![11](https://user-images.githubusercontent.com/5687907/131232945-4ef45a33-1473-481c-b51f-40ad9ccd23be.jpg)

**Comment by komainu8** [comment]
Thank you for your report.
I'm updating now.

**Comment by kou** [comment]
Updated.
