### ISSUE TITLE
mysql-8.0.29-12.04 が期待通りに動作しない

### ISSUE THREAD

**Issue by gaeeyo** [mroonga/docker#74]
こんにちは。
mysql-8.0.29-12.04 を試したところ、通常は初回起動時に行われる設定が行われず、mroonga が有効になりませんでした。

```
$ docker run --rm groonga/mroonga:mysql-8.0.29-12.04
```

```
2022-06-22 04:21:34+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1debian10 started.
2022-06-22 04:21:34+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-06-22 04:21:34+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1debian10 started.
```

通常であればデータベースが存在しないため、初期化の処理が走り、そこで「MYSQL_ROOT_PASSWORD が設定されていない」など、いろんなチェックにひっかかるはずなのですが、何も表示されません。

調べたところ、mysql-8.0.29-12.04 の Dockerfile で mysql-community-8.0-mroonga がインストールされたときに、すでに /var/lib/mysql の中身が作成されていました。
このため新しい volume を /var/lib/mysql に設定しても、もともとの /var/lib/mysql の内容が volume にコピーされるので初期設定の処理が実行されませんでした。

```
$ docker run --rm -v vol1:/var/lib/mysql groonga/mroonga:mysql-8.0.29-12.04
```

nocopy を付けるとコピーが行われないのでうまく動作しました。(これを調べるまで、デフォルトでコピーされることを知りませんでした...)

```
$ docker run --rm -v vol1:/var/lib/mysql:nocopy groonga/mroonga:mysql-8.0.29-12.04
```

また、古いバージョンのタグの mysql-8.0.28-12.02 は正常に動作しましたが、MySQL のバージョンが 8.0.28 ではなく、5.7.37 でした。

**Comment by komainu8** [comment]
たしかに有効になりませんね。。。調べてみます。
ご報告ありがとうございます！！

＞ また、古いバージョンのタグの mysql-8.0.28-12.02 は正常に動作しましたが、MySQL のバージョンが 8.0.28 ではなく、5.7.37 でした。

上記は https://github.com/mroonga/docker/commit/1901b400eae26a2b0f2a03f62bb85187572bf4d2 で修正した問題だと思います。

**Comment by kou** [comment]
`groonga/mroonga:mysql-8.0-latest`で毎回DBを作成するようにしておきました。

MroongaのUDFが登録されていないんですが、それは https://github.com/mroonga/mroonga/issues/509 と同じ話なので次のリリースで直るはずです。
